[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-moon_os.json"

[target.x86_64-moon_os]
rustflags = ["-C", "link-arg=-Tlinker.ld"]
